-- 表的数据: wp_dict_data(1/1) 每页: 1000 --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('1', '1', 'field_type', 'varchar', 'varchar', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('2', '1', 'field_type', 'int', 'int', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('3', '1', 'field_type', 'tinyint', 'tinyint', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('4', '1', 'field_type', 'smallint', 'smallint', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('5', '1', 'field_type', 'mediumint', 'mediumint', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('6', '1', 'field_type', 'bigint', 'bigint', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('7', '1', 'field_type', 'decimal', 'decimal', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('8', '1', 'field_type', 'char', 'char', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('9', '1', 'field_type', 'text', 'text', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('10', '1', 'field_type', 'tinytext', 'tinytext', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('11', '1', 'field_type', 'mediumtext', 'mediumtext', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('12', '1', 'field_type', 'longtext', 'longtext', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('13', '2', 'form_type', '文本框', 'text', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('14', '2', 'form_type', '文本域', 'textarea', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('15', '2', 'form_type', '下拉框', 'select', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('16', '2', 'form_type', '单选框', 'radio', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('17', '2', 'form_type', '开关', 'switch', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('18', '2', 'form_type', '编辑器', 'editor', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('19', '2', 'form_type', '日期', 'date', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('20', '2', 'form_type', '日期时间', 'datetime', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('21', '2', 'form_type', '单图上传', 'image', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('22', '2', 'form_type', '多选框', 'selects', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('23', '3', 'form_verify', '可空', 'nullable', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('24', '3', 'form_verify', '必填', 'required', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('25', '3', 'form_verify', '手机号', 'phone', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('26', '3', 'form_verify', '邮箱', 'email', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('27', '3', 'form_verify', '网址', 'url', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('28', '3', 'form_verify', '数字', 'number', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('29', '3', 'form_verify', '日期', 'date', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('30', '3', 'form_verify', '身份证', 'identity', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('31', '4', 'user_sex', '男', '1', '1', '1');-- <fen> --
INSERT INTO `wp_dict_data` (`id`, `dict_id`, `dict_name`, `label`, `value`, `sort`, `status`) VALUES ('32', '4', 'user_sex', '女', '2', '1', '1');-- <fen> --
